### ISSUE TITLE
Player data saves

### ISSUE THREAD

**Issue by JakeRyan1** [amakuu/xrp#2]
Player data saves when you are not in the server i was away for a couple of hours console was spammed with saving user. Also when you leave and rejoin the server it will show 2, 3, 4 player saves for the same user if you have not restarted the server. 
![image](https://user-images.githubusercontent.com/29259524/69835842-76333480-1212-11ea-8cc8-c48a174c63c7.png)

**Comment by amakuu** [comment]
Fixed in [#0cb666c](https://github.com/amakuu/xrp/commit/0cb666cbf8d95479c8fa494c9d25d0a52e774908?diff=unified)
